### ISSUE TITLE
Empty vuid

### ISSUE THREAD

**Issue by kovava** [notum-cz/strapi-plugin-content-versioning#122] opened 2023-09-05 12:35 UTC
### Describe the bug

In v0.4.10 when I create a new entry and click Save button (not Save as a new version) the entry got created but in the database vuid field is empty, which leads to problems when I want to create other items in the same collection (they simply got hidden from the UI because considered different versions of the same entry)

Note, after I rolled back to v0.4.7 it works properly again

### Steps to reproduce the behavior

1. In Admin UI create a collection type which supports versioning
2. Patch which makes "Save" button to behave as "save as a new version" should NOT be applied
3. In Admin UI create a new entry and click Save
4. Check database table which contains entries

### Expected behavior

vuid filed should be populated for newly created entry

### Screenshots

![image](https://github.com/notum-cz/strapi-plugin-content-versioning/assets/8371104/314458c8-a05a-4641-812c-988aeee499fd)

### System

- Node.js version: 16.14.2
- NPM version: 8.5.0
- Strapi version: 4.9.0
- Database: postgres
- Operating system: Ununtu

**Comment by kovava** [comment] 2023-09-05 12:44
Behavior looks very similar to one described in #104

**Comment by kovava** [comment] 2023-09-06 09:39
@omikulcik looks quite confusing.... On your screenshots I see that vuid is NULL for all the entries. Is that expected? At the same time I see that all records has is_visible_in_list_view. Looks like v0.4.7 populated vuid for all the entries but stopped doing that in later versions...

From what I saw in my app it looks that vuid was used as the ID which identifies the entry. So creating the 2nd entry with empty vuid made the previous one switching is_visible_in_list_view to false (I believe thinking that it's just another version of the entry identified by vuid=NULL) and preventing it appearing in the UI...

**Comment by omikulcik** [comment] 2023-09-07 06:39
@omikulcik I think this might be a problem of a specific version of Strapi. I rember that some versions around 4.9.0 had problems with filtering by attributes that are not visible such as this one.  More context here:

`      _.set(attributes, "isVisibleInListView", {
        writable: true,
        private: false,
        configurable: false,
        visible: false,
        type: "boolean",
        default: true,
      });`
      
   `        ctx.request.query.filters = {
          $and: [{ is_visible_in_list_view: { $eq: true } }],
          ...ctx.request.query.filters,
        };`
        

Could you please try upgrading to newer version of Strapi just to see if this persists?

**Comment by robsonpiere** [comment] 2023-09-15 22:56
I had the same problem. I added a new item by clicking the save button.
The version number was added with 1 but the vuid was empty

![image](https://github.com/notum-cz/strapi-plugin-content-versioning/assets/11904136/86c217cb-dc09-4a8b-84f1-fabacc0294ab)

**Strapi version**: 4.13.6
**Plugin version**: 0.4.11 - Patch for save button not applied.

**Comment by omikulcik** [comment] 2023-09-18 06:31
@robsonpiere The steps to reproduce are the same as @kovava mentioned please? I still can not reproduce this behaviour.

**Comment by JDFIREX** [comment] 2023-09-18 11:06
@omikulcik 
I think this error is caused by removing the content of beforeCreate 
https://github.com/notum-cz/strapi-plugin-content-versioning/commit/00420ec63fb68b0cefc6568cac1e66cfeecf989a#diff-a1273db013e51519f612e2b7b820638c2ddfcf8ca2049ea12a1f9bfeead3fb48

Now every time you create a new object ("Draft" ) the vuid in the database is null 
Publishing the object will cause the script in beforeUpdate to set the isVisibleInListView flag to false for evey object with null value in vuid 
![image](https://github.com/notum-cz/strapi-plugin-content-versioning/assets/42634156/df4310ee-3514-4817-9819-ffed4a5d82b7)
BeforeCreate does not create a unique vuid for us
This causes all new objects with null to disappear from the list by the fact that they all have null 
![image](https://github.com/notum-cz/strapi-plugin-content-versioning/assets/42634156/e0818804-b074-4279-bb21-ba92d6a78eba)

The only option to create sie vuid is to click the button 
![image](https://github.com/notum-cz/strapi-plugin-content-versioning/assets/42634156/45bce2dd-66e5-43ea-adba-08a95b789977)

But it seems to me that it should create a vuid for an object during creation and not by clicking on a new version button

**Comment by robsonpiere** [comment] 2023-09-18 13:47
> @robsonpiere The steps to reproduce are the same as @kovava mentioned please? I still can not reproduce this behaviour.

Yes, 

1. I create a basic collection with one field only;
2. In Content type add a new item, and save (using native strapi button)
3. Checkec on postgres database, the vuid was `null`, but the version number is `1`

**Comment by omikulcik** [comment] 2023-09-25 07:29
Hi guys, we have just published a new version that removes the need to patch strapi admin and works and uses entity service decorator. Can you please test whether this problem still persists in this newer version?

**Comment by robsonpiere** [comment] 2023-09-26 21:55
@omikulcik I tested it and it's ok now.

**Comment by omikulcik** [comment] 2023-10-02 06:10
@robsonpiere Thank you very much for testing. I am closing this issue since is seems it has been solved

**Closed by omikulcik** 2023-10-02 06:10 UTC
Labels: issue: bug, status: can not reproduce
