### ISSUE TITLE
Delete removes every entity in collection

### ISSUE THREAD

**Issue by Adaphath** [notum-cz/strapi-plugin-content-versioning#143] opened 2023-10-25 07:41 UTC
### Describe the bug

When deleting a single entity, every entity in the collection gets removed.

### Expected behavior

Only remove selected entity.

### System

- Node.js version: v18.15.0
- NPM version:
- Strapi version: 4.14.2
- Database: mysql
- Operating system: Ubuntu

### Additional context

We activated draft / publish on the collection and are not able to disable the plugin cause otherwise all entities are removed as well.

**Comment by omikulcik** [comment] 2023-10-30 13:43
Hello @Adaphath ,

 thank you for reporting this issue. Could you please provide more detailed steps to reproduce it? I've just tried and was not able to reproduce. I created 3 versions of entity in a collection.
 
<img width="986" alt="image" src="https://github.com/notum-cz/strapi-plugin-content-versioning/assets/44231035/1ccf6616-58eb-4cfb-9716-c01a8073afe7">

Then I deleted one.

<img width="941" alt="image" src="https://github.com/notum-cz/strapi-plugin-content-versioning/assets/44231035/7679a057-afe4-454e-977a-8f9603f6bd01">


And only one version was deleted.

**Comment by Adaphath** [comment] 2023-10-31 16:33
Hi there,
thank you for your response.

I think we somehow misconfigured the plugin, because it did not create a valid vuid. It was always `null`.
This lead to multiple versions and entities with the same vuid and therefore deleted everything.
The problem is the reproduction of it. For now, we manually added vuids and then disabled the plugin entirely to not run into this issue again.

**Comment by omikulcik** [comment] 2023-11-01 09:03
Hi @Adaphath ,

so it seems this is user specific issue so I am closing this.

**Closed by omikulcik** 2023-11-01 09:03 UTC
