### ISSUE TITLE
Error Validation is not working properly

### ISSUE THREAD

**Issue by maruthasalamr** [notum-cz/strapi-plugin-content-versioning#84] opened 2023-05-10 11:50 UTC
Hi,
Please help us,
As as strapi admin i want to create multiple version of the content using strapi content versioning.When i save a content as new version the API is directly called and throws if there any error in prompt Message component.But the native save button will validates and shows the error in the  input fields instantly.

Steps to reproduce the behavior
1.Open content Manager
2.Select any collection type and click editany content.
3.click save a a new version "Button".
4.You will receive Error prompt message instant of showing the message in the input field.
5.If you click regular save button the validation message is shown in the input field itself.   

 

 Expected behavior

![Image 10-05-23 at 5 17 PM](https://github.com/notum-cz/strapi-plugin-content-versioning/assets/78694065/8b9088a2-f0e1-46bf-ba14-9cf7a482674c)

 Current behavior

![Image 10-05-23 at 5 19 PM](https://github.com/notum-cz/strapi-plugin-content-versioning/assets/78694065/37e8fc2d-f3fb-4291-a1eb-901aec8d8182)

System
- Node.js version:  14.19.1
- NPM version:9.2.0
- Strapi version: 4.9.1
- Database: postgres
- Operating system: Mac Os

**Comment by maruthasalamr** [comment] 2023-05-11 13:48
@martincapek  Please help us with the above bug

**Comment by omikulcik** [comment] 2023-06-23 09:23
Hi @maruthasalamr,

this is probably caused by the fact that we are manipulating function of the native save button in patches. We are currently working on publishing a new version in which it will not be needed to use patches. This upcoming release has the potential to resolve the problem you've encountered

**Comment by omikulcik** [comment] 2023-10-02 09:43
Hello, we have released a new version that uses the native button to save new version of the content so It should be fine now. Closing this.

**Closed by omikulcik** 2023-10-02 09:43 UTC
Labels: issue: bug, severity: low
